In [13]:
import pandas as pd

catchment_info = pd.read_csv('/home/mettalbi/projects/smash-maintenance-1.0.x/tests/results/catchment_infos.csv')
catchment_info

,id,area,mean_annual_rainfall,mean_annual_pet,mean_hourly_discharge,slope,drainage_density,karst_zone,forest_cover,urban_cover,potential_water_reserve,high_storage_capacity,mean_soil_moisture,aridity_index,missing_data
0,K003002010,227.0,1198.556144,514.926973,1.504665,0.991743,16.906130,0.000000,0.503828,0.000000,307.01160,0.190410,0.466352,2.327624,0.0
1,K201082001,48.8,1205.560710,539.132161,1.426142,1.173790,18.686491,0.000000,0.880025,0.000000,325.20465,0.000000,0.428362,2.236114,0.0
2,O163401001,196.0,631.760707,799.850730,0.854948,0.119805,18.502970,0.000000,0.094784,0.000000,230.93651,0.000000,0.331381,0.789848,0.0
3,O331401002,42.9,1552.753335,571.759956,2.031174,1.736611,18.600690,0.000000,0.868664,0.000000,156.51079,0.000000,0.435730,2.715743,0.0
4,V352401001,380.0,733.664227,653.976768,2.541941,1.671473,14.043176,0.000000,0.516340,0.049900,245.72229,0.000000,0.440477,1.121851,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,Y561503001,279.0,994.775855,718.899532,3.987777,2.136573,12.832941,0.862877,0.383266,0.231841,215.96349,0.598782,0.399082,1.383748,0.0
122,Y604201001,676.0,904.312964,509.379458,11.453833,5.310582,20.131207,0.450890,0.447800,0.200635,165.84174,0.000000,0.454813,1.775323,0.0
123,Y612501201,1064.0,881.537992,543.018058,13.072386,5.352664,20.491238,0.319288,0.482363,0.138719,176.31046,0.000000,0.420526,1.623405,0.0
124,Y642401001,262.0,952.256322,630.198831,3.301544,4.004024,20.606953,0.140254,0.819613,0.013184,198.00003,0.000000,0.370740,1.511041,0.0
125,Y643401001,451.0,968.393217,663.897632,5.215410,4.207306,18.677004,0.282339,0.754303,0.011098,199.80695,0.060231,0.389199,1.458648,0.0

In [22]:
catchment_info.describe()

,area,mean_annual_rainfall,mean_annual_pet,mean_hourly_discharge,slope,drainage_density,karst_zone,forest_cover,urban_cover,potential_water_reserve,high_storage_capacity,mean_soil_moisture,aridity_index,missing_data
count,126.000000,126.000000,126.000000,126.000000,126.000000,126.000000,126.000000,126.000000,126.000000,126.000000,126.000000,126.000000,126.000000,126.0
mean,402.985716,896.333125,726.479102,5.392676,2.091782,17.782119,0.416686,0.529311,0.047737,198.263520,0.126644,0.371898,1.273176,0.0
std,415.253789,248.738398,87.816090,7.228438,1.321106,3.504252,0.342659,0.216550,0.075472,51.621820,0.203047,0.051810,0.451829,0.0
min,28.000000,510.936973,490.319245,0.066604,0.007540,9.820255,0.000000,0.074676,0.000000,48.000000,0.000000,0.258672,0.598428,0.0
25%,131.500000,717.317647,662.282730,0.876861,1.134716,15.795741,0.086646,0.387083,0.005712,174.017930,0.000000,0.331582,0.903403,0.0
50%,239.000000,821.822533,741.459218,2.459940,2.006961,17.765580,0.366178,0.553018,0.018479,200.153770,0.000244,0.372928,1.170412,0.0
75%,559.000000,1017.763538,793.139408,6.700134,2.979873,19.124014,0.739829,0.696930,0.045596,229.786435,0.194455,0.414690,1.526464,0.0
max,1958.000000,1552.753335,883.080078,49.167408,5.352664,28.942920,1.000000,0.940721,0.507210,327.472470,0.824665,0.466352,2.715743,0.0

In [26]:
catchment_info['slope'].value_counts()

slope
2.413292    2
0.886989    2
1.134716    2
2.117569    1
2.152038    1
           ..
4.169264    1
3.669932    1
2.077148    1
2.123094    1
4.207306    1
Name: count, Length: 123, dtype: int64